USE `COMPANY`;
SELECT CONCAT(E.Fname,' ',E.Minit,' ',E.Lname) AS 'Full name', E.SSN AS ssn, D.DNUMBER AS 'Dept. Id', D.DNAME AS 'Dept. Name'
FROM EMPLOYEE AS E, DEPARTMENT AS D
WHERE E.SSN = D.MGR_SSN AND D.DNUMBER IN 
(
	SELECT DISTINCT P.DNUM 
    FROM WORKS_ON AS W,
    PROJECT AS p
    WHERE W.PNO = P.PNUMBER 
    GROUP BY W.ESSN, P.DNUM
    HAVING SUM(HOURS) < 40
);