USE `COMPANY`;
SELECT CONCAT(FNAME, ' ', MINIT, ' ', LNAME) AS 'Full name', SSN AS 'ssn', SUPERVISED  AS 'Dept. Number of employees'
FROM EMPLOYEE AS E,
(
	SELECT SUPER_SSN, COUNT(*) AS SUPERVISED
	FROM EMPLOYEE
	WHERE SUPER_SSN IS NOT NULL
	GROUP BY SUPER_SSN
) 
AS D
WHERE E.SSN = D.SUPER_SSN
ORDER BY SUPERVISED;