USE `COMPANY`;
SELECT ESSN AS 'Manager ssn',COUNT(PNO) AS 'Number of projects' 
FROM WORKS_ON WHERE ESSN=
(
    SELECT MGR_SSN FROM DEPARTMENT WHERE DNUMBER=
    (
        SELECT DNUM FROM PROJECT WHERE PNAME='ProductY'
    )
) GROUP BY ESSN;