USE `COMPANY`;
SELECT D.DNUMBER AS 'Dept. Id', D.DNAME AS 'Dept. Name', count(L.DLOCATION) AS 'Number of locations'
FROM DEPARTMENT D, DEPT_LOCATIONS L
WHERE D.DNUMBER=L.DNUMBER and D.MGR_SSN IN
(
    SELECT D1.ESSN
    FROM DEPENDENT D1
    WHERE D1.SEX='F'
    GROUP BY D1.ESSN
    HAVING COUNT(*)>=2
)
GROUP BY L.DNUMBER;