USE `COMPANY`;
SELECT D1.ESSN AS 'Manager ssn',  D2.DNUMBER AS 'Dept. Id', COUNT(*) AS 'Number of Dependents'
FROM DEPENDENT D1, DEPARTMENT D2
WHERE D2.MGR_SSN=D1.ESSN
GROUP BY D1.ESSN,D2.DNUMBER
HAVING D1.ESSN IN 
(
	SELECT D3.MGR_SSN
	FROM DEPARTMENT D3
	WHERE D3.DNUMBER=
    (
		SELECT DNUMBER 
        FROM DEPT_LOCATIONS 
        GROUP BY DNUMBER HAVING COUNT(*) > 1
	) 
);